using static Sortings;
using static Files;
using static Recursive;
using static Strings;
using static Functions;

// Проверки всех функций
Sortings sortings = new Sortings();
sortings.StartSorting();
Files files = new Files();
files.CreateFile();
Recursive recursive = new Recursive();
Console.WriteLine(recursive.IntArray(10));
recursive = new Recursive();
Console.WriteLine(recursive.IntArrayReverse(10));
recursive = new Recursive();
Console.WriteLine(recursive.IntArraySum(10));
recursive = new Recursive();
recursive.Fibonacci(0, 1, 1, 10);
Console.WriteLine(recursive.Power(5, 3));
Strings strings = new Strings();
Console.WriteLine(strings.SelfMadeLengthChecker("hello"));
strings.CountUnique("Hello 117!");
Console.WriteLine(strings.StringEqualityCheck("hey", "hey"));
Console.WriteLine(strings.StringEqualityCheck("hey", "ho"));
Console.WriteLine(strings.StringEqualityCheck("lets", "goooo"));
Console.WriteLine(strings.SubstringCounter("“привет привет мой дорогой друг”", "привет"));
strings.AuthChecker();
Functions functions = new Functions();
Console.WriteLine(functions.GetMonthByNumber(3));
Console.WriteLine(functions.ReturnCharCode('A'));
functions.ArrayToStrings(new List<object>() { "hello", 1811, "goodbye" });
Console.WriteLine(functions.CalculateOneInBinaryRepresentation(12));
functions.ArrayToIntArray(new List<object>() { 881, "laugh", 16, "b", "k", "programming" });